// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: rsi.proto

package rsiclient

import (
	"context"

	"mcp_service/pb/rsi"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetRsiRequest  = rsi.GetRsiRequest
	GetRsiResponse = rsi.GetRsiResponse

	Rsi interface {
		GetRsi(ctx context.Context, in *GetRsiRequest, opts ...grpc.CallOption) (*GetRsiResponse, error)
	}

	defaultRsi struct {
		cli zrpc.Client
	}
)

func NewRsi(cli zrpc.Client) Rsi {
	return &defaultRsi{
		cli: cli,
	}
}

func (m *defaultRsi) GetRsi(ctx context.Context, in *GetRsiRequest, opts ...grpc.CallOption) (*GetRsiResponse, error) {
	client := rsi.NewRsiClient(m.cli.Conn())
	return client.GetRsi(ctx, in, opts...)
}
