// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: services/rsi/rsi.proto

package rsi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRsiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRsiRequest) Reset() {
	*x = GetRsiRequest{}
	mi := &file_services_rsi_rsi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRsiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRsiRequest) ProtoMessage() {}

func (x *GetRsiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_rsi_rsi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRsiRequest.ProtoReflect.Descriptor instead.
func (*GetRsiRequest) Descriptor() ([]byte, []int) {
	return file_services_rsi_rsi_proto_rawDescGZIP(), []int{0}
}

func (x *GetRsiRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetRsiRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

type GetRsiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Rsi           float32                `protobuf:"fixed32,2,opt,name=rsi,proto3" json:"rsi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRsiResponse) Reset() {
	*x = GetRsiResponse{}
	mi := &file_services_rsi_rsi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRsiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRsiResponse) ProtoMessage() {}

func (x *GetRsiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_rsi_rsi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRsiResponse.ProtoReflect.Descriptor instead.
func (*GetRsiResponse) Descriptor() ([]byte, []int) {
	return file_services_rsi_rsi_proto_rawDescGZIP(), []int{1}
}

func (x *GetRsiResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetRsiResponse) GetRsi() float32 {
	if x != nil {
		return x.Rsi
	}
	return 0
}

var File_services_rsi_rsi_proto protoreflect.FileDescriptor

const file_services_rsi_rsi_proto_rawDesc = "" +
	"\n" +
	"\x16services/rsi/rsi.proto\x12\x03rsi\"C\n" +
	"\rGetRsiRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\":\n" +
	"\x0eGetRsiResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x10\n" +
	"\x03rsi\x18\x02 \x01(\x02R\x03rsi28\n" +
	"\x03Rsi\x121\n" +
	"\x06GetRsi\x12\x12.rsi.GetRsiRequest\x1a\x13.rsi.GetRsiResponseB\aZ\x05./rsib\x06proto3"

var (
	file_services_rsi_rsi_proto_rawDescOnce sync.Once
	file_services_rsi_rsi_proto_rawDescData []byte
)

func file_services_rsi_rsi_proto_rawDescGZIP() []byte {
	file_services_rsi_rsi_proto_rawDescOnce.Do(func() {
		file_services_rsi_rsi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_rsi_rsi_proto_rawDesc), len(file_services_rsi_rsi_proto_rawDesc)))
	})
	return file_services_rsi_rsi_proto_rawDescData
}

var file_services_rsi_rsi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_rsi_rsi_proto_goTypes = []any{
	(*GetRsiRequest)(nil),  // 0: rsi.GetRsiRequest
	(*GetRsiResponse)(nil), // 1: rsi.GetRsiResponse
}
var file_services_rsi_rsi_proto_depIdxs = []int32{
	0, // 0: rsi.Rsi.GetRsi:input_type -> rsi.GetRsiRequest
	1, // 1: rsi.Rsi.GetRsi:output_type -> rsi.GetRsiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_rsi_rsi_proto_init() }
func file_services_rsi_rsi_proto_init() {
	if File_services_rsi_rsi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_rsi_rsi_proto_rawDesc), len(file_services_rsi_rsi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_rsi_rsi_proto_goTypes,
		DependencyIndexes: file_services_rsi_rsi_proto_depIdxs,
		MessageInfos:      file_services_rsi_rsi_proto_msgTypes,
	}.Build()
	File_services_rsi_rsi_proto = out.File
	file_services_rsi_rsi_proto_goTypes = nil
	file_services_rsi_rsi_proto_depIdxs = nil
}
