// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: services/rsi/rsi.proto

package rsi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rsi_GetRsi_FullMethodName = "/rsi.Rsi/GetRsi"
)

// RsiClient is the client API for Rsi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RsiClient interface {
	GetRsi(ctx context.Context, in *GetRsiRequest, opts ...grpc.CallOption) (*GetRsiResponse, error)
}

type rsiClient struct {
	cc grpc.ClientConnInterface
}

func NewRsiClient(cc grpc.ClientConnInterface) RsiClient {
	return &rsiClient{cc}
}

func (c *rsiClient) GetRsi(ctx context.Context, in *GetRsiRequest, opts ...grpc.CallOption) (*GetRsiResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRsiResponse)
	err := c.cc.Invoke(ctx, Rsi_GetRsi_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RsiServer is the server API for Rsi service.
// All implementations must embed UnimplementedRsiServer
// for forward compatibility.
type RsiServer interface {
	GetRsi(context.Context, *GetRsiRequest) (*GetRsiResponse, error)
	mustEmbedUnimplementedRsiServer()
}

// UnimplementedRsiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRsiServer struct{}

func (UnimplementedRsiServer) GetRsi(context.Context, *GetRsiRequest) (*GetRsiResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRsi not implemented")
}
func (UnimplementedRsiServer) mustEmbedUnimplementedRsiServer() {}
func (UnimplementedRsiServer) testEmbeddedByValue()             {}

// UnsafeRsiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RsiServer will
// result in compilation errors.
type UnsafeRsiServer interface {
	mustEmbedUnimplementedRsiServer()
}

func RegisterRsiServer(s grpc.ServiceRegistrar, srv RsiServer) {
	// If the following call panics, it indicates UnimplementedRsiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rsi_ServiceDesc, srv)
}

func _Rsi_GetRsi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRsiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RsiServer).GetRsi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rsi_GetRsi_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RsiServer).GetRsi(ctx, req.(*GetRsiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rsi_ServiceDesc is the grpc.ServiceDesc for Rsi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rsi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rsi.Rsi",
	HandlerType: (*RsiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRsi",
			Handler:    _Rsi_GetRsi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/rsi/rsi.proto",
}
