// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: position.proto

package server

import (
	"context"

	"mcp_service/pb/position"
	"mcp_service/services/position/internal/logic"
	"mcp_service/services/position/internal/svc"
)

type PositionServer struct {
	svcCtx *svc.ServiceContext
	position.UnimplementedPositionServer
}

func NewPositionServer(svcCtx *svc.ServiceContext) *PositionServer {
	return &PositionServer{
		svcCtx: svcCtx,
	}
}

func (s *PositionServer) GetPosition(ctx context.Context, in *position.GetPositionRequest) (*position.PositionList, error) {
	l := logic.NewGetPositionLogic(ctx, s.svcCtx)
	return l.GetPosition(in)
}
