// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: price.proto

package server

import (
	"context"

	"mcp_service/pb/price"
	"mcp_service/services/price/internal/logic"
	"mcp_service/services/price/internal/svc"
)

type PriceServiceServer struct {
	svcCtx *svc.ServiceContext
	price.UnimplementedPriceServiceServer
}

func NewPriceServiceServer(svcCtx *svc.ServiceContext) *PriceServiceServer {
	return &PriceServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PriceServiceServer) GetPrice(ctx context.Context, in *price.Symbol) (*price.Price, error) {
	l := logic.NewGetPriceLogic(ctx, s.svcCtx)
	return l.GetPrice(in)
}
