// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: price.proto

package priceservice

import (
	"context"

	"mcp_service/pb/price"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Price  = price.Price
	Symbol = price.Symbol

	PriceService interface {
		GetPrice(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Price, error)
	}

	defaultPriceService struct {
		cli zrpc.Client
	}
)

func NewPriceService(cli zrpc.Client) PriceService {
	return &defaultPriceService{
		cli: cli,
	}
}

func (m *defaultPriceService) GetPrice(ctx context.Context, in *Symbol, opts ...grpc.CallOption) (*Price, error) {
	client := price.NewPriceServiceClient(m.cli.Conn())
	return client.GetPrice(ctx, in, opts...)
}
