// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: rsi.proto

package server

import (
	"context"

	"mcp_service/pb/rsi"
	"mcp_service/services/rsi/internal/logic"
	"mcp_service/services/rsi/internal/svc"
)

type RsiServer struct {
	svcCtx *svc.ServiceContext
	rsi.UnimplementedRsiServer
}

func NewRsiServer(svcCtx *svc.ServiceContext) *RsiServer {
	return &RsiServer{
		svcCtx: svcCtx,
	}
}

func (s *RsiServer) GetRsi(ctx context.Context, in *rsi.GetRsiRequest) (*rsi.GetRsiResponse, error) {
	l := logic.NewGetRsiLogic(ctx, s.svcCtx)
	return l.GetRsi(in)
}
