// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: proto/position/position.proto

package position

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionRequest) Reset() {
	*x = GetPositionRequest{}
	mi := &file_proto_position_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionRequest) ProtoMessage() {}

func (x *GetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_position_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionRequest.ProtoReflect.Descriptor instead.
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return file_proto_position_position_proto_rawDescGZIP(), []int{0}
}

type PositionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*PositionDetail      `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionList) Reset() {
	*x = PositionList{}
	mi := &file_proto_position_position_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionList) ProtoMessage() {}

func (x *PositionList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_position_position_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionList.ProtoReflect.Descriptor instead.
func (*PositionList) Descriptor() ([]byte, []int) {
	return file_proto_position_position_proto_rawDescGZIP(), []int{1}
}

func (x *PositionList) GetPositions() []*PositionDetail {
	if x != nil {
		return x.Positions
	}
	return nil
}

type PositionDetail struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Symbol           string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity         string                 `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EntryPrice       string                 `protobuf:"bytes,3,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	UnrealizedPnl    string                 `protobuf:"bytes,4,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	LiquidationPrice string                 `protobuf:"bytes,5,opt,name=liquidation_price,json=liquidationPrice,proto3" json:"liquidation_price,omitempty"`
	Side             string                 `protobuf:"bytes,6,opt,name=side,proto3" json:"side,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PositionDetail) Reset() {
	*x = PositionDetail{}
	mi := &file_proto_position_position_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionDetail) ProtoMessage() {}

func (x *PositionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_position_position_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionDetail.ProtoReflect.Descriptor instead.
func (*PositionDetail) Descriptor() ([]byte, []int) {
	return file_proto_position_position_proto_rawDescGZIP(), []int{2}
}

func (x *PositionDetail) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionDetail) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *PositionDetail) GetEntryPrice() string {
	if x != nil {
		return x.EntryPrice
	}
	return ""
}

func (x *PositionDetail) GetUnrealizedPnl() string {
	if x != nil {
		return x.UnrealizedPnl
	}
	return ""
}

func (x *PositionDetail) GetLiquidationPrice() string {
	if x != nil {
		return x.LiquidationPrice
	}
	return ""
}

func (x *PositionDetail) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

var File_proto_position_position_proto protoreflect.FileDescriptor

const file_proto_position_position_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/position/position.proto\x12\bposition\"\x14\n" +
	"\x12GetPositionRequest\"F\n" +
	"\fPositionList\x126\n" +
	"\tpositions\x18\x01 \x03(\v2\x18.position.PositionDetailR\tpositions\"\xcd\x01\n" +
	"\x0ePositionDetail\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\tR\bquantity\x12\x1f\n" +
	"\ventry_price\x18\x03 \x01(\tR\n" +
	"entryPrice\x12%\n" +
	"\x0eunrealized_pnl\x18\x04 \x01(\tR\runrealizedPnl\x12+\n" +
	"\x11liquidation_price\x18\x05 \x01(\tR\x10liquidationPrice\x12\x12\n" +
	"\x04side\x18\x06 \x01(\tR\x04side2O\n" +
	"\bPosition\x12C\n" +
	"\vGetPosition\x12\x1c.position.GetPositionRequest\x1a\x16.position.PositionListB\fZ\n" +
	"./positionb\x06proto3"

var (
	file_proto_position_position_proto_rawDescOnce sync.Once
	file_proto_position_position_proto_rawDescData []byte
)

func file_proto_position_position_proto_rawDescGZIP() []byte {
	file_proto_position_position_proto_rawDescOnce.Do(func() {
		file_proto_position_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_position_position_proto_rawDesc), len(file_proto_position_position_proto_rawDesc)))
	})
	return file_proto_position_position_proto_rawDescData
}

var file_proto_position_position_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_position_position_proto_goTypes = []any{
	(*GetPositionRequest)(nil), // 0: position.GetPositionRequest
	(*PositionList)(nil),       // 1: position.PositionList
	(*PositionDetail)(nil),     // 2: position.PositionDetail
}
var file_proto_position_position_proto_depIdxs = []int32{
	2, // 0: position.PositionList.positions:type_name -> position.PositionDetail
	0, // 1: position.Position.GetPosition:input_type -> position.GetPositionRequest
	1, // 2: position.Position.GetPosition:output_type -> position.PositionList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_position_position_proto_init() }
func file_proto_position_position_proto_init() {
	if File_proto_position_position_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_position_position_proto_rawDesc), len(file_proto_position_position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_position_position_proto_goTypes,
		DependencyIndexes: file_proto_position_position_proto_depIdxs,
		MessageInfos:      file_proto_position_position_proto_msgTypes,
	}.Build()
	File_proto_position_position_proto = out.File
	file_proto_position_position_proto_goTypes = nil
	file_proto_position_position_proto_depIdxs = nil
}
