// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: services/price/price.proto

package price

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Symbol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_services_price_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_services_price_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_services_price_price_proto_rawDescGZIP(), []int{0}
}

func (x *Symbol) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Price struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Price) Reset() {
	*x = Price{}
	mi := &file_services_price_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_services_price_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_services_price_price_proto_rawDescGZIP(), []int{1}
}

func (x *Price) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Price) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_services_price_price_proto protoreflect.FileDescriptor

const file_services_price_price_proto_rawDesc = "" +
	"\n" +
	"\x1aservices/price/price.proto\x12\x05price\" \n" +
	"\x06Symbol\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"5\n" +
	"\x05Price\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price27\n" +
	"\fPriceService\x12'\n" +
	"\bGetPrice\x12\r.price.Symbol\x1a\f.price.PriceB\tZ\a./priceb\x06proto3"

var (
	file_services_price_price_proto_rawDescOnce sync.Once
	file_services_price_price_proto_rawDescData []byte
)

func file_services_price_price_proto_rawDescGZIP() []byte {
	file_services_price_price_proto_rawDescOnce.Do(func() {
		file_services_price_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_price_price_proto_rawDesc), len(file_services_price_price_proto_rawDesc)))
	})
	return file_services_price_price_proto_rawDescData
}

var file_services_price_price_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_price_price_proto_goTypes = []any{
	(*Symbol)(nil), // 0: price.Symbol
	(*Price)(nil),  // 1: price.Price
}
var file_services_price_price_proto_depIdxs = []int32{
	0, // 0: price.PriceService.GetPrice:input_type -> price.Symbol
	1, // 1: price.PriceService.GetPrice:output_type -> price.Price
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_price_price_proto_init() }
func file_services_price_price_proto_init() {
	if File_services_price_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_price_price_proto_rawDesc), len(file_services_price_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_price_price_proto_goTypes,
		DependencyIndexes: file_services_price_price_proto_depIdxs,
		MessageInfos:      file_services_price_price_proto_msgTypes,
	}.Build()
	File_services_price_price_proto = out.File
	file_services_price_price_proto_goTypes = nil
	file_services_price_price_proto_depIdxs = nil
}
