// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: position.proto

package position_client

import (
	"context"

	"mcp_service/pb/position"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetPositionRequest = position.GetPositionRequest
	PositionDetail     = position.PositionDetail
	PositionList       = position.PositionList

	Position interface {
		GetPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*PositionList, error)
	}

	defaultPosition struct {
		cli zrpc.Client
	}
)

func NewPosition(cli zrpc.Client) Position {
	return &defaultPosition{
		cli: cli,
	}
}

func (m *defaultPosition) GetPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*PositionList, error) {
	client := position.NewPositionClient(m.cli.Conn())
	return client.GetPosition(ctx, in, opts...)
}
